# Lista de símbolos para monitoramento (Scanner)
# Focado em Perpetual Futures (Bybit linear)
SYMBOLS = [
    'BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'ADAUSDT', 'XRPUSDT', 'DOTUSDT', 'DOGEUSDT', 'AVAXUSDT', 'LINKUSDT',
    '1000SHIBUSDT', 'MATICUSDT', 'LTCUSDT', 'UNIUSDT', 'TRXUSDT', 'ATOMUSDT', 'ETCUSDT', 'BCHUSDT', 'FILUSDT', 'LDOUSDT',
    'APTUSDT', 'NEARUSDT', 'ARBUSDT', 'OPUSDT', 'STXUSDT', 'GRTUSDT', 'FTMUSDT', 'RENDERUSDT', '1000PEPEUSDT', 'INJUSDT',
    'SUIUSDT', 'TIAUSDT', 'SEIUSDT', 'BEAMUSDT', 'ORDIUSDT', '1000BONKUSDT', 'WIFUSDT', '1000FLOKIUSDT', 'JUPUSDT', 'PYTHUSDT',
    'RNDRUSDT', 'FETUSDT', 'AGIXUSDT', 'OCEANUSDT', 'NEARUSDT', 'IMXUSDT', 'ALGOUSDT', 'HBARUSDT', 'VETUSDT', 'SANDUSDT',
    'MANAUSDT', 'AXSUSDT', 'THETAUSDT', 'EOSUSDT', 'AAVEUSDT', 'SNXUSDT', 'MKRUSDT', 'CRVUSDT', 'DYDXUSDT', 'GMXUSDT',
    'WOOUSDT', 'JASMYUSDT', 'GALAUSDT', 'FLOWUSDT', 'CHZUSDT', 'KAVAUSDT', 'ROSEUSDT', 'CFXUSDT', 'MINAUSDT', 'IOTAUSDT',
    'ZILUSDT', 'ENJUSDT', 'KNCUSDT', '1INCHUSDT', 'LRCUSDT', 'ANKRUSDT', 'MASKUSDT', 'GLMRUSDT', 'MOVRUSDT', 'METISUSDT',
    'LUNA2USDT', 'USTCUSDT', '1000LUNCUSDT', 'RUNEUSDT', 'STGUSDT', 'LQTYUSDT', 'IDUSDT', 'EDUUSDT', 'MAVUSDT', 'ARKMUSDT',
    'WLDUSDT', 'CYBERUSDT', 'NTRNUSDT', 'MEMEUSDT', 'ORDIUSDT', 'BLURUSDT', 'BIGTIMEUSDT', 'GASUSDT', 'TRBUSDT', 'STORJUSDT',
    'BLZUSDT', 'LOOMUSDT', 'HIFIUSDT', 'FRONTUSDT', 'VGXUSDT', 'REEFUSDT', 'SFPUSDT', 'CELOUSDT', 'ZENUSDT', 'QTUMUSDT',
    'NEOUSDT', 'ONTUSDT', 'BATUSDT', 'ZRXUSDT', 'OMGUSDT', 'WAVESUSDT', 'ICXUSDT', 'IOSTUSDT', 'GLMUSDT', 'KSMUSDT',
    'QTUMUSDT', 'DASHUSDT', 'ZECUSDT', 'XMRUSDT', 'LRCUSDT', 'RENUSDT', 'BALUSDT', 'COMPUSDT', 'SUSHIUSDT', 'YFIUSDT',
    'CRVUSDT', 'CVXUSDT', 'SPELLUSDT', 'LPTUSDT', 'BANDUSDT', 'UMAUSDT', 'TRUUSDT', 'RLCUSDT', 'CTSIUSDT', 'DENTUSDT',
    '1000WINUSDT', '1000BTTUSDT', 'CKBUSDT', 'RVNUSDT', 'SCUSDT', 'HOTUSDT', 'XVGUSDT', 'DGBUSDT', 'SYSUSDT', 'CELRUSDT',
    'NKNUSDT', 'ONEUSDT', 'COTIUSDT', 'CHRUSDT', 'STMXUSDT', 'ALPHAUSDT', 'DUSKUSDT', 'BELUSDT', 'MTLUSDT', 'LINAUSDT'
]
